#!/bin/bash

SCRIPT_NAME=$0
COMMAND=$1
SEBPI_SETUP_FILE_NAME="sebpi-setup.sh"
SEBPI_UPDATE_FILE_NAME="sebpi-update.sh"
RASPI_IP_ADDRESS="192.168.1.2"

function usage() {
    echo "Usage: $SCRIPT_NAME <install|setup>"
    return 1
}

function fail() {
    echo "$SCRIPT_NAME error: $1"
    exit 1
}

function confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

function install() {
    if [[ "$#" -ne 2 ]]; then
        echo "Usage: $SCRIPT_NAME install <img_file> <dev_disk>"
        echo "Example: $SCRIPT_NAME install raspbian-stretch-lite.img /dev/rdisk3"
        return 1
    fi

    local IMG_FILE="$1"
    local DEV_DISK="$2"

    confirm "WARNING: This will erase completely the contents of the SD card at $DEV_DISK. Do you want to proceed? [y/N]" || return -1

    sudo diskutil eraseDisk FAT32 RASPBIAN MBRFormat ${DEV_DISK/r/} || fail "Could not erase ${DEV_DISK/r/}"
    sleep 5
    diskutil unmountdisk ${DEV_DISK/r/} || fail "Could not unmount ${DEV_DISK/r/}"

    echo "Copying $IMG_FILE to $DEV_DISK..."
    sleep 5
    sudo dd if="$IMG_FILE" of=$DEV_DISK bs=1m || fail "Could not copy $IMG_FILE onto $DEV_DISK"
    sleep 5
    sudo touch /Volumes/boot/ssh || fail "Could not touch file /boot/ssh"
    cp "$SEBPI_SETUP_FILE_NAME" /Volumes/boot
    cp "$SEBPI_UPDATE_FILE_NAME" /Volumes/boot
    diskutil unmountdisk ${DEV_DISK/r/} || fail "Could not unmount ${DEV_DISK/r/}"
    sed -i '' "/^$RASPI_IP_ADDRESS /d" ~/.ssh/known_hosts

    echo "Done! To continue:"
    echo "  1. Insert your microSD card in the Raspberry Pi and turn it on."
    echo "  2. Wait 5 minutes (seriously)."
    echo "  3. Come back to this terminal here and run 'sebpi setup'"

    return 0
}

function setup() {
    if [[ "$#" -gt 0 ]]; then
        local PUSHBULLET_API_KEY="$1"
    fi

    sed -i '' "/^$RASPI_IP_ADDRESS /d" ~/.ssh/known_hosts

    echo "Running $SEBPI_SETUP_FILE_NAME on the Raspberry Pi..."
    ssh -t pi@$RASPI_IP_ADDRESS "sudo /boot/$SEBPI_SETUP_FILE_NAME $PUSHBULLET_API_KEY"

    echo "Please change the password (default: raspberry)"
    ssh -t pi@$RASPI_IP_ADDRESS "passwd"

    return 0
}

case "$COMMAND" in
    install)
        install $2 $3;
        ;;
    setup)
        setup $2;
        ;;
    *)
        usage;
        ;;
esac
